[colors]
[colors.primary]
foreground = "#ebdbb2"
background = "#282828"

[colors.dim]
red = "#aa1d18"
green = "#767614"
yellow = "#d65d0e"
blue = "#376a6d"
magenta = "#9d4d71"
cyan = "#578558"
white = "#bdae93"

[colors.normal]
black = "#3c3836"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#d5c4a1"

[colors.bright]
black = "#504945"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#fbf1c7"
