[window]
padding = { x = 0, y = 0 }
dimensions = { columns = 98, lines = 24 }
dynamic_padding = true
decorations = "None"
opacity = 1
title = "O_o"

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
bold = { family = "JetBrainsMonoNerdFont", style = "Bold" }
italic = { family = "JetBrainsMonoNerdFont", style = "Italic" }
size = 12

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_timeout = 0

[general]
import = [ "~/.config/alacritty/themes/Gruv.toml" ]
